
name: Codeforces Sync
on:
  schedule:
    - cron: '0 * * * *'  # Runs hourly
  workflow_dispatch:     # Manual trigger option

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Run sync script
        run: |
          pip install requests
          python sync_script.py
          
      - name: Commit changes
        run: |
          git config --global user.name "CF Sync Bot"
          git add problems/
          git commit -m "Update solved problems" || echo "No changes to commit"
          git push
